version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: trienkhai
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodsic
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: afyra/cuoiki-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/moodsic
      SPRING_DATASOURCE_USERNAME: trienkhai
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    image: afyra/cuoiki-frontend:latest
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  db_data:
