# file: prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'backend-app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['backend:8080']
